jupyterlab/jupyterlab-demo

environment.yml, tasks.py
This updates the instructions for jlab 0.25
=> Update the environment for jlab 0.25

.travis.yml, tasks.py
@blink1073 I couldn't figure out how to push to @jasongrout 's branch so I'm making the PR again.  Also added docstrings to the invoke scripts
=> adding --no-build flag and docstrings

narrative/scipy2017.md, notebooks/Fasta.ipynb, tasks.py
Here is a small script that set things up for the scipy 2017 lightning talk.
=> Set up the scipy2017 lightning talk files.

LICENSE
Making organization names consistent.
=> License Org Name

appveyor.yml, environment.yml, tasks.py
Fixes #35 and adds Appveyor testing.
=> Add Windows Support

data/Dockerfile
This can be used to demonstrate automatic language detection for syntax highlighting in JupyterLab.
=> Add an example dockerfile

appveyor.yml, environment.yml
=> Reinstate tensorflow

notebooks/Lorenz.ipynb, notebooks/lorenz.py
This is a simplified notebook from the poster-child example for the notebook, the ipywidgets Lorenz demonstration. I simplified it slightly to make it easy to take a screenshot containing both the equations and the interact.
CC @ellisonbg
=> Add the Lorenz differential equation notebooks we use in screenshots.

README.md
Added Urban Data Challenge License
=> Urban Data Challenge License in README

binder/apt.txt
To demo terminal in JupyterLab
=> Add a terminal text editor

README.md
=> Tiny typo fix in README

.travis.yml, binder/environment.yml, tasks.py
https://mybinder.org/v2/gh/blink1073/jupyterlab-demo/jlab-0.34?urlpath=lab
=> Update for jlab 0.34

narrative/jupyterlab.md
quick fix to typo in introduction text
=> [SCIPY19] fixing narrative typo

narrative/jupyterlab.md
cleaning up contributor notes in demo narrative
=> cleaning up contributor text

tasks.py
#94 
Remove plotly lab extension.
=> Remove plotly extension

binder/environment.yml, jupyter_notebook_config.py
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/krassowski/jupyterlab-demo/rtc-demo?urlpath=lab)
=> Update for 3.1 with RTC mode enabled

.binder/environment.yml, .github/workflows/main.yml, .github/workflows/update_env.yml, README.md, tasks.py
Add GitHub workflow to check manually or periodically (once a month) updates.
=> Add workflow to update the environment

.github/workflows/main.yml
=> Add browser check

tasks.py
=> Don't use unix commands

.binder/environment.yml
Since Notebook 7 final has now been released.
=> Use `notebook=7.0.4`

.binder/environment.yml
This should fix the check environment workflow: https://github.com/jupyterlab/jupyterlab-demo/actions/runs/6873556312
=> Fix notebook spec
